# Python for Codacy

---

exclude_paths:
    - 'examples/**'
    - 'tests/**'
    - 'docs/**'

pylint:
    enabled: true
    config:
        disable:
            - D400
pydocstyle:
    enabled: true
    config:
        conventions:
            - "numpy"
            - "pep257"
        add-ignore:
            - D400