strictness: veryhigh
max-line-length: 79
doc-warnings: yes

ignore-paths:
    - .github
    - build
    - docs
    - examples
    - tests

requirements:
    - requirements.txt

pylint:
    run: false

pyflakes:
    run: false

mccabe:
    run: false

pep8:
    run: true

pep257:
    run: true

pydocstyle:
    run: true
    disable:
        - D203
        - D204
        - D205
        - D212
        - D213
        - D400
        - D415
        - N803