doc-warnings: yes
strictness: veryhigh
max-line-length: 70
requirements:
    - requirements.txt
pylint:
    run: false
pyflakes:
    run: false
mccabe:
    run: false
pep8:
    disable:
      - E501
pep257:
    disable:
      - D203
      - D205
      - D212
      - D213
      - D406
      - D407