strictness: veryhigh
max-line-length: 79
doc-warnings: yes

exclude:
    - 'tests/**'
    - 'docs/**'
    - '.github/**'

requirements:
    - requirements.txt

pylint:
    run: false

pyflakes:
    run: false

mccabe:
    run: false

pep8:
    run: true

pep257:
    run: true

pydocstyle:
    run: true
    disable:
        - D204
        - D205
        - D212
        - D213
        - D400